backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: 'public/uploads' # Where media files will be stored
public_folder: '/uploads' # Where the media files can be accessed from the server

collections:
  - name: 'blog' # Used in routes, e.g., /admin/collections/blog
    label: 'Blog' # Used in the UI
    folder: 'content/blogs' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          date_format: 'DD.MM.YYYY',
          time_format: 'HH:mm',
          format: 'LLL',
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: Image, name: image, widget: image, required: false }
      - { label: Heading, name: heading, widget: string }
      - { label: Subheading, name: subheading, widget: string }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'content/pages/index.md'
        label: 'Landing Page'
        name: 'index'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - label: 'Gallery'
            name: 'galleryImages'
            widget: 'list'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: Image, name: image, widget: image }
              - { label: 'Alt Text', name: 'alt', widget: 'string' }
              - { label: 'Text', name: 'text', widget: 'markdown' }

      - file: 'content/pages/about/index.md'
        label: 'About'
        name: 'about'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - label: 'Profile'
            name: 'profileGallery'
            widget: 'list'
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: Image, name: image, widget: image }
              - { label: 'Alt Text', name: 'alt', widget: 'string' }
              - { label: 'Text', name: 'text', widget: 'markdown' }

      - file: 'content/pages/application/index.md'
        label: 'Application'
        name: 'application'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }

      - file: 'content/pages/legal/index.md'
        label: 'Legal'
        name: 'legal'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - {
              label: 'Publish Date',
              name: 'date',
              widget: 'datetime',
              date_format: 'DD.MM.YYYY',
              time_format: 'HH:mm',
              format: 'LLL',
            }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: Image, name: image, widget: image, required: false }

      - file: 'content/pages/gallery/index.md'
        label: 'Image Gallery'
        name: 'gallery'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - label: 'Gallery'
            name: 'imageGallery'
            widget: 'list'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: Image, name: image, widget: image }
              - { label: 'Alt Text', name: 'alt', widget: 'string' }
              - { label: 'Text', name: 'text', widget: 'markdown' }
